config/routes.rb
Rails.application.routes.draw do
 

  resources :rentals
      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rental.rb
class Rental < ApplicationRecord
    validates :property, presence: true
    validates :rent, presence: true, numericality: { only_integer: true }, length: { minimum: 5 } 
    validates :address, presence: true
    validates :age, presence: true, numericality: { only_integer: true }
    validates :remarks, presence: true
    has_many :stations, dependent: :destroy
    accepts_nested_attributes_for :stations
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :rental, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
    before_action :set_rental, only:[:show, :edit, :update, :destroy]
  
  def new
      @rental = Rental.new
      2.times {@rental.stations.build}
  end
  
  def create
      @rental = Rental.new(rental_params)
      respond_to do |format|
          if @rental.save
              format.html { redirect_to @rental, notice: 'Rent property was successfully created.' }
              format.json { render :show, status: :created, location: @rental }
              else
              format.html { render :new }
              format.json { render json: @rental.errors, status: :unprocessable_entity }
          end
      end
  end
  
  def index
      @rentals = Rental.all
  end
  
  def show
      @stations = Station.where(rental_id: set_rental.id).all
  end
  
  def edit
      @rental.stations.build
  end
  
  def update
      respond_to do |format|
          if @rental.update(rental_params)
              format.html { redirect_to @rental, notice: 'Rent property was successfully updated.' }
              format.json { render :show, status: :ok, location: @rental }
              else
              format.html { render :edit }
              format.json { render json: @rental.errors, status: :unprocessable_entity }
          end
      end
  end
  
  def destroy
      @rental.destroy
      redirect_to rentals_path, notice:"削除しました"
  end
  
  private
  
  def rental_params
      params.require(:rental).permit(:property, :rent, :address, :age, :remarks,stations_attributes: [:id, :_destroy, :rental_id, :route_name, :station_name, :walking_minutes])
  end
  
  def set_rental
      @rental = Rental.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/_form.html.erb
<%= form_for(@rental) do |f| %>


  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    物件名<br>
    <%= f.text_field :property%><br><br>
    賃料<br>
    <%= f.text_field :rent %>円<br><br>
    住所<br>
    <%= f.text_field :address %><br><br>
    築年数<br>
    <%= f.text_field :age %>年<br><br>
    備考<br>
    <%= f.text_area :remarks %>
    <hr>

    <% x = 1 %>
    <%= f.fields_for :stations do |s| %>
    <h3>最寄り駅<%= x %></h3>
    路線名<br>
    <%= s.text_field :route_name %><br><br>
    駅名<br>
    <%= s.text_field :station_name %><br><br>
    徒歩分数<br>
    <%= s.text_field :walking_minutes %>分<br><br>
    <% x += 1 %>
    <% end %>
    <br>
    <%= f.submit "登録する" %><br>
    <%= link_to "戻る", rentals_path %>

<% end %>

app/views/rentals/edit.html.erb
<h1>編集</h1>
<h2>物件編集</h2>

<%= render 'form' %>

app/views/rentals/index.html.erb
<h1>一覧</h1>
<hr>
<h2>物件一覧</h2>
<p><%= notice %></p>

<table>
  <tr>
    <th>物件名 &emsp; </th>
    <th>賃料 &emsp; </th>
    <th>住所 &emsp; </th>
    <th>築年数 &emsp; </th>
    <th>備考 &emsp; </th>
  </tr>

  <% @rentals.each do |r| %>
   <tr>
     <td><%= r.property %>&emsp; </td>
     <td><%= r.rent %>円 &emsp; </td>
     <td><%= r.address %>&emsp; </td>
     <td><%= r.age %>年 &emsp; </td>
     <td><%= r.remarks %>&emsp; </td>
     <td><%= link_to '詳細', rental_path(r.id) %> &emsp;</td>
     <td><%= link_to '編集', edit_rental_path(r.id) %> &emsp;</td>
     <td><%= link_to '削除', rental_path(r.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
   </tr>
   <% end %>

</table>
<%= link_to "物件を登録する", new_rental_path %>

app/views/rentals/new.html.erb
<h1>登録</h1>
<h2>物件登録</h2>

<%= render 'form' %>

app/views/rentals/show.html.erb
<h1>閲覧</h1>
<hr>
    <b>物件名</b>：<%= @rental.property %><br><br>
    <b>賃料</b>：<%= @rental.rent %>円<br><br>
    <b>住所</b>：<%= @rental.address %><br><br>
    <b>築年数</b>：<%= @rental.age %>年<br><br>
    <b>備考</b>：<%= @rental.remarks %><br><br>
  <hr>
  <% @stations.each_with_index do |st, i| %>
  <h3>最寄り駅<%= "#{i+1}" %></h3>
    <b>路線名</b>&nbsp;<%= st.route_name %><br><br>
    <b>駅名</b>&nbsp;<%= st.station_name %><br><br>
    <b>徒歩分数</b>&nbsp;<%= st.walking_minutes %>分<br><br>
<% end %><br>
<%= link_to "戻る", rentals_path %>